### ISSUE TITLE
[Question]: LemonLoader support?

### ISSUE THREAD

**Issue by dimbox-idk** [yukieiji/UnityExplorer#36]
### Describe the issue

Will it work on [LemonLoader](https://github.com/LemonLoader/MelonLoader)?

**Comment by yukieiji** [comment]
May be no. Also, it would be difficult to support.

 - reason
   - UE doesn't work with MelonLoader v0.6.5 (bug on MelonLoader)
   - I don't think it will work correctly because it embeds the C# runtime compiler with ilpack
   - I seem to remember that the mod loader DLLs etc. were loaded by a custom load logic, so I think that's what's not working.

**Comment by yukieiji** [comment]
@dimbox-idk I'll close it, is that a problem?

**Comment by yukieiji** [comment]
Closed due to no reply
